
services:
  store:
    build:
      context: .
      dockerfile: Dockerfile
      # Ajout pour ARM64
      platforms:
        - linux/arm64
    container_name: hackathon4-store-app
    ports:
      - "8080:8080"  # On remet sur 8080 pour la cohérence
    environment:
      # Configuration base de données
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/hackathon4_db
      SPRING_DATASOURCE_USERNAME: api_user
      SPRING_DATASOURCE_PASSWORD: secure_password_123
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      
      # Configuration JPA
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: false
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      
      # Configuration serveur
      SERVER_PORT: 8080
      
      # Health checks et monitoring
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,metrics
      MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: always
      
      # Application
      APP_NAME: Hackathon4 Store API
      APP_VERSION: 1.0.0
    depends_on:
      db:
        condition: service_healthy  # Attendre que la DB soit vraiment prête
    networks:
      - app-network
    restart: unless-stopped
    # Health check pour le container
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  db:
    # Version spécifique pour ARM64
    image: postgres:15-alpine
    container_name: hackathon4-postgres
    environment:
      POSTGRES_DB: hackathon4_db
      POSTGRES_USER: api_user
      POSTGRES_PASSWORD: secure_password_123
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Optionnel : scripts d'initialisation
      # - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network
    restart: unless-stopped
    # Health check pour PostgreSQL
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U api_user -d hackathon4_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
