---
- name: Install Java 17 Amazon Corretto
  dnf:
    name: java-17-amazon-corretto-devel
    state: present

- name: Set JAVA_HOME environment variable
  lineinfile:
    path: /etc/environment
    line: 'JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto'
    create: yes

- name: Verify Java installation
  command: java -version
  register: java_version
  changed_when: false

- name: Display Java version
  debug:
    var: java_version.stderr
