all:
  children:
    bastion:
      hosts:
        bastion-host:
          ansible_host: 15.237.82.57
          ansible_port: 4222
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/hackathon4_rsa
    
    internal_services:
      hosts:
        jenkins-server:
          ansible_host: 10.0.1.170
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/hackathon4_rsa
          ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q -i ~/.ssh/hackathon4_rsa ec2-user@15.237.82.57 -p 4222" -o StrictHostKeyChecking=no'
        
        api-server:
          ansible_host: 10.0.1.33
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/hackathon4_rsa
          ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q -i ~/.ssh/hackathon4_rsa ec2-user@15.237.82.57 -p 4222" -o StrictHostKeyChecking=no'
          
        kong-server:
          ansible_host: 10.0.1.248
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/hackathon4_rsa
          ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q -i ~/.ssh/hackathon4_rsa ec2-user@15.237.82.57 -p 4222" -o StrictHostKeyChecking=no'

  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_host_key_checking: false
