all:
  hosts:
    jenkins-server:
      ansible_host: 10.0.1.170
      ansible_user: ec2-user
      
    api-server:
      ansible_host: 10.0.1.33
      ansible_user: ec2-user
      
    kong-server:
      ansible_host: 10.0.1.248
      ansible_user: ec2-user

  vars:
    ansible_ssh_private_key_file: ~/.ssh/hackathon4_rsa
    ansible_python_interpreter: /usr/bin/python3
